enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: true
header-transparent: true
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
custom_logo:
  user/themes/quark/images/logo/Logo-Dany-Ocean_ws-1.png:
    name: Logo-Dany-Ocean_ws-1.png
    type: image/png
    size: 3108
    path: user/themes/quark/images/logo/Logo-Dany-Ocean_ws-1.png
